language: php

services:
  - mysql

php:
  - 7.2

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --dev --prefer-source --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS greenhubfarmer_testing;'
  - php artisan migrate --seed --env=testing
  - yarn install

script:
  - composer ci-test
