version: "3.7"
services:
  mariadb-database:
    image: mariadb:10.4
    container_name: mariadb-database
    environment:
      MYSQL_ROOT_PASSWORD: homestead
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - "./create_tables.sql:/docker-entrypoint-initdb.d/1.sql"
    #  - ./deploy/development/database/scripts/mysql/install.sh:/docker-entrypoint-initdb.d/install.sh
    #  - ./deploy/development/database/scripts/mysql/data/:/dev-data/
    #  - ./deploy/development/database/scripts/mysql/dummy_inserts.sh/:/dummy_inserts.sh